### ISSUE TITLE
Marka doesn't working with bundlers

### ISSUE THREAD

**Issue by ghost** [KingPixil/marka#2]

**Comment by kbrsh** [comment]
This project is discontinued, I'd recommend `marked` or something similar. Marka is not reliable at all for edge cases.

If you'd like, you can fork this and create your own version.

**Comment by ghost** [comment]
Thank you for response :)

**Comment by ghost** [comment]
I just found great alternative =) It's [snarkdown](https://github.com/developit/snarkdown)

**Comment by kbrsh** [comment]
Nice! :raised_hands:
